name: Build APK
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          ZIP=$(ls *.zip | head -n1)
          unzip -o "$ZIP" -d src
      - run: |
          cd src
          cd $(ls -d */ | head -n1)
          chmod +x gradlew
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Athanase-APK
          path: src/**/build/outputs/apk/debug/*.apk
