name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o athanase-library.zip
          if [ -d "athanase-library1" ]; then mv athanase-library1/*.; fi
          if [ -d "athanase-library" ]; then mv athanase-library/*.; fi
          ls -la

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          chmod +x./gradlew
         ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Athanase-APK
          path: app/build/outputs/apk/debug/*.apk
